#!/usr/bin/env node

'use strict';

const fs = require('fs');
const path = require('path');

const async = require('async');
const mysql = require('mysql');
const _ = require('underscore');

const ERROR = 'error';

//let fnTest = () => {

let oJSON = {};

let isAccumulated = (ts) => {
  if (_.isString(ts)) {
    let index = ts.indexOf('ACCUMULATED');
    if (index > -1) {
      return true
    }
  }

  return false;
};

try {
  let src = path.join(__dirname, '..', 'app.config');
  let data = fs.readFileSync(src);
  let s = data.toString();
  oJSON = JSON.parse(s);
} catch(e) {
  let src = path.join(__dirname, '..', 'app.config');
  console.log(src);
  return
}

let args = process.argv;
let last = args.length - 1;

let variablesOut = {};

if (last > -1) {
  let sID = args[last];
  let id = parseInt(sID);
  if (_.isNaN(id)) {
    console.log(ERROR);
    return;
  }

  if (!_.isNumber(id)) {
    console.log(ERROR);
    return;
  }

  const connSW = mysql.createConnection({
    host: oJSON.DB_HOST_SW,
    user: oJSON.DB_USER_SW,
    password: oJSON.DB_PWD_SW,
    database: oJSON.DB_NAME_SW,
  });

  async.waterfall([
    (fn) => {
      connSW.connect((err) => {
        if (err) {
          console.error('error connecting:' + err.stack);
          fn(true)
          return;
        }

        fn();
        return;
      });
    },
    (fn) => {
      let query = `SELECT * FROM records_requests WHERE id = ?;`
      connSW.query(query, [id], (err, results, fields) => {
        if (err) {
          fn(true);
          return;
        }

        if (results.length == 0) {
          fn(true);
          return;
        }

        let result = results[0];
        let sJSON = result.json;
        fn(null, sJSON);
      });
    },
    (sJSON, fn) => {
      connSW.end(() => {
        connSW.destroy();
        fn(null, sJSON);
        return;
      });
    }
  ], (err, sJSON) => {
    if (err) {
      console.log(ERROR);
      return;
    }

    let variablesIn = [];

    try {
      variablesIn = JSON.parse(sJSON);
    } catch (e) {
      console.log(ERROR);
      return;
    }

    async.each(variablesIn, (variableIn, next) => {

      let o = {};

      let key = variableIn.key;
      let wheres = variableIn.wheres;
      let is_avg = variableIn.is_avg;

      o[key] = (fun) => {
        const connection = mysql.createConnection({
          host: oJSON.DB_HOST_RECODS,
          user: oJSON.DB_USER_RECODS,
          password: oJSON.DB_PWD_RECODS,
          database: oJSON.DB_NAME_RECODS,
          timezone: 'Z',
          multipleStatements: true
        });

        async.waterfall([
          (fn) => {
            connection.connect((err) => {
              if (err) {
                console.error('error connecting:' + err.stack);
                fn(true)
                return;
              }

              fn();
              return;
            });
          },
          (fn) => {
            let qs = {};
            for (let i = 0; i < wheres.length; i++) {
              const where = wheres[i];
              qs[i] = (f) => {

                let tables = [];
                if (where.tables) {
                  tables = where.tables;
                }

                let rows = [];

                let isAvgV = _.clone(is_avg);
                let isHighest = false;
								

                if (tables.length > 1) {
                  isAvgV = false;
                }

                async.eachSeries(tables, (table, last) => {
                  if (isAccumulated(where.gte)) {
                    isAvgV = false;
                    isHighest = true;

                    where.gte = where.gte.replace('ACCUMULATED', '')
                  }

                  let query = `SELECT * FROM ${table} WHERE timestamp >= ? AND timestamp < ? ORDER BY timestamp ASC;`
                  if (isAvgV) {
                    query = `SELECT AVG(value) AS value FROM ${table} WHERE timestamp >= ? AND timestamp < ?;`
                  }

                  connection.query(query, [where.gte, where.lt], (err, results) => {
                    if (err) {
                      last();
                      return;
                    }

                    if (results.length == 0) {
                      last();
                      return;
                    }

                    rows = rows.concat(results);
                    last();
                    return;
                  });
                }, () => {
                  // ALL VALUES
                  if (!is_avg) {
                    let rowsOut = [];

                    let size = rows.length;
                    for (let i = 0; i < size; i++) {
                      const r = rows[i];

                      let row = {
                        id: r.id,
                        v: r.value,
                        t: r.timestamp
                      };

                      rowsOut.push(row);
                    }

                    f(null, rowsOut);
                    return;
                  }

                  // HIGHEST
                  if (isHighest) {
                    let rowsOut = [];
                    let valueHighest = 0;
                    let timestamp = where.gte;
                    let id = 0;

                    let size = rows.length;
                    if (size == 1) {
                      const r = rows[0];
                      valueHighest = r.value;

                    } else if (size > 1) {
                      for (let i = 0; i < size; i++) {
                        const r = rows[i];
                        if (r.value > valueHighest) {
                          valueHighest = r.value;
                        }
                      }
                    }

                    if (_.isNaN(valueHighest) || _.isNull(valueHighest)) valueAvg = 0;

                    timestamp = timestamp.replace(' ', 'T');
                    timestamp = timestamp + 'Z';

                    let row = {
                      id: id,
                      v: valueHighest,
                      t: timestamp
                    };

                    rowsOut.push(row);

                    f(null, rowsOut);
                    return;
                  }

                  // AVG
                  let rowsOut = [];
                  let valueAvg = 0;
                  let timestamp = where.gte;
                  let id = 0;

                  let size = rows.length;
                  if (size == 1) {
                    const r = rows[0];
                    valueAvg = r.value;

                  } else if (size > 1) {
                    for (let i = 0; i < size; i++) {
                      const r = rows[i];
                      if (r.value > 0) {
                        valueAvg = valueAvg + r.value;
                      }
                    }

                    valueAvg = valueAvg / size;
                  } else {
                    /*
                      DEPRECATED PARA MOSTRAR ROW VACIOS O SEGMENTOS SIN DATOS
                      f(null, rowsOut);
                      return;
                    */
                  }

                  if (_.isNaN(valueAvg) || _.isNull(valueAvg)) valueAvg = 0;

                  timestamp = timestamp.replace(' ', 'T');
                  timestamp = timestamp + 'Z';

                  let row = {
                    id: id,
                    v: valueAvg,
                    t: timestamp
                  };

                  rowsOut.push(row);

                  f(null, rowsOut);
                });
              };
            }

            async.parallel(qs, (err, r) => {
              let res = [];

              for (let i = 0; i < wheres.length; i++) {
                let rows = r[i];

                for (let j = 0; j < rows.length; j++) {
                  const row = rows[j];
                  let o = {
                    v: row.v,
                    t: row.t
                  };

                  if (row.id) o.id = row.id;

                  res.push(o);
                }
              }

              fn(null, res);
            });
          },
          (results, fn) => {
            connection.end(() => {
              connection.destroy();
              fn(null, results);
              return;
            });
          }
        ], (err, results) => {
          if (err) {
            fun(null, []);
            return;
          }

          fun(null, results);
          return;
        });
      };

      if (_.isEmpty(o)) {
        variablesOut[key] = [];
        next();
        return;
      }

      async.parallel(o, (err, results) => {
        variablesOut[key] = results[key];
        next();
        return;
      });

    }, () => {
      let variables = [];
      for (const key in variablesOut) {
        if (variablesOut.hasOwnProperty(key)) {
          const records = variablesOut[key];
          let o = {
            variable: key,
            records: records
          };
          variables.push(o);
        }
      }

      let s = JSON.stringify(variables);
      console.log(s);
    });

  });

} else {
  console.log(ERROR);
  return;
}

//};